services:
  - type: worker
    name: shorteninglinkbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DATABASE_NAME
        value: bot_database.db
      - key: TIMEZONE
        value: UTC
